server:
  port: 8081

spring:
  application:
    name: COSMIC-BHARAT

  data:
    mongodb:
      uri: mongodb+srv://abhishek539700_db_user:VKaqecTIGZghsROh@cluster0.my3oemr.mongodb.net/CosmicBharat?retryWrites=true&w=majority&appName=Cluster0